---
title: "The Social Norms behind Inaction and Why Remaining Stagnant Can Make You Regret"
author: Janssen Myer Rambaud
thanks: "Code and data are available at: https://github.com/foreverwoods/The-Normality-of-Action-Inaction-and-How-They-Interact-with-Regret; Replication on Social Science Reproduction platform available at: "
date: today
date-format: long
abstract: "The general idea regarding the concept of regret can be summarized with the famous phrase of 'Don't do something you may regret'. This paper aims to tackle this misconceived notion by presenting inaction."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)

```

# Introduction

As humans, we are all familiar with the general feeling of regret. For the most part these regrets are caused by mistakes on our part, but other times, they can also be the result of not taking action. The saying, 'hindsight is 20/20', is one specific example that can be attributed to this feeling of regret. Before diving deeper into this topic, it is best to begin with a definition of regret and inaction. According to psychology and behaviour scholar Marcel Zeelenberg, regret is defined as, "the negative, cognitively based emotion that we experience when realizing or imagining that our present situation would have been better had we acted differently" (Roos 2023) While inaction can be defined simply as not taking action or not acting upon something. This here drives a question of why, as humans, feel that way. Researcher Gilad Feldman interprets this feeling to be influenced by normality, specifically, societal norms in general (Feldman 2019).

Diving deeper into this topic, it is actually possible to look into what can attribute to a 'quantifiable' amount of regret. This can be called 'perceived regret'. While it is true that every person will feel a different level of regret, and even then, it would be difficult to express just how much 'regret' one has, it would be wise to gather a fairly larger group of people to tackle the possible problem of bias. As such, multiple experiments were conducted by Feldman under a simple question and rating system. This is where the calculation of perceived regret is conducted. The participants were provided scenarios and asked questions pertaining a particular party in the scenario and what they believe their 'perceived regret' is.

By presenting a fixed scenario in these experiments, each participant can answer in a more rational, yet personalized manner. If you were to ask them to recall their own experiences for the sake of gathering a variety of responses/scenarios, the data could possibly be all over the place. Each person has their own experiences, some consisting of extreme regret, while others do not. These are problems that could possibly influence the data in some manner. It is important to consider this idea of inaction because it is something that we do in our lives, and something we will continue to do as we go on in life. I am looking to validate Feldman's claims that normality plays a crucial role in impacting the perception of regret. The research was studied on undergraduate Hong Kong students as well as hired MTurk participants. The estimand in question is the perceived regret that stems from inaction and how societal norms come into play. This paper aims to follow a reproduction of Feldman's research and findings, but dwell deeper onto the side of inaction and norm theory rather than the comparison between action and inaction.


# Data {#sec-data}

Using R from @citeR as the programming language, we can conduct research based on the research provided by Gilad Feldman in his journal article, "What is normal? Dimensions of action-inaction normality and their impact on regret in the action-effect" (@feldmanRegrets) as well as the data from the experiments (@feldmanDataset), we can dive deeper into the concept of inaction. Other articles were also used, such as @regretDefinition in order to give a sound understanding to our topic.


# Model

The goal of our modelling strategy is twofold. Firstly,...

Here we briefly describe the Bayesian analysis model used to investigate... Background details and diagnostics are included in 
## Model set-up



### Model justification



# Results



# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this.

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {.unnumbered}

# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check


## Diagnostics


\newpage

# References
